/home/remote/pogo_pull/run.sh: line 5: python3.6: command not found
/home/remote/pogo_pull/run.sh: line 6: python3.6: command not found
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
