/home/remote/pogo_pull/run.sh: line 5: python3.6: command not found
/home/remote/pogo_pull/run.sh: line 6: python3.6: command not found
